<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.16">
  <compounddef id="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException" kind="class" language="C#" prot="public">
    <compoundname>Cqrs::Azure::DocumentDb::DocumentDbException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException_a19e08be1e69ac87230e739e784f3c6b6_1a19e08be1e69ac87230e739e784f3c6b6" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>Cqrs.Azure.DocumentDb.DocumentDbException.DocumentDbException</definition>
        <argsstring>(string message, Exception exception)</argsstring>
        <name>DocumentDbException</name>
        <param>
          <type>string</type>
          <declname>message</declname>
        </param>
        <param>
          <type>Exception</type>
          <declname>exception</declname>
        </param>
        <briefdescription>
<para>Instantiate a new instance of <ref refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException" kindref="compound">DocumentDbException</ref> with a specified error message and a reference to the inner <emphasis>exception</emphasis>  that is the cause of this Exception. </para>
        </briefdescription>
        <detaileddescription>
<para><parameterlist kind="param"><parameteritem>
<parameternamelist>
<parametername>message</parametername>
</parameternamelist>
<parameterdescription>
<para>The error message that explains the reason for the exception.</para>
</parameterdescription>
</parameteritem>
<parameteritem>
<parameternamelist>
<parametername>exception</parametername>
</parameternamelist>
<parameterdescription>
<para>The Exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner Exception is specified.</para>
</parameterdescription>
</parameteritem>
</parameterlist>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" line="24" column="8" bodyfile="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" bodystart="24" bodyend="27"/>
      </memberdef>
      <memberdef kind="function" id="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException_a0fe55ab6d2a689b055460557d4f50fe7_1a0fe55ab6d2a689b055460557d4f50fe7" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>Cqrs.Azure.DocumentDb.DocumentDbException.DocumentDbException</definition>
        <argsstring>(Exception exception)</argsstring>
        <name>DocumentDbException</name>
        <param>
          <type>Exception</type>
          <declname>exception</declname>
        </param>
        <briefdescription>
<para>Instantiate a new instance of <ref refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException" kindref="compound">DocumentDbException</ref> with a reference to the inner <emphasis>exception</emphasis>  that is the cause of this Exception. </para>
        </briefdescription>
        <detaileddescription>
<para><parameterlist kind="param"><parameteritem>
<parameternamelist>
<parametername>exception</parametername>
</parameternamelist>
<parameterdescription>
<para>The Exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner Exception is specified.</para>
</parameterdescription>
</parameteritem>
</parameterlist>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" line="33" column="8" bodyfile="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" bodystart="33" bodyend="36"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>A non-fault tolerant Exception while interacting with DocumentDB. </para>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>Cqrs.Azure.DocumentDb.DocumentDbException</label>
        <link refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>Cqrs.Azure.DocumentDb.DocumentDbException</label>
        <link refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" line="18" column="1" bodyfile="/opt/buildAgent/work/565751ca98ebc594/Framework/Azure/Cqrs.Azure.DocumentDb/DocumentDbException.cs" bodystart="17" bodyend="37"/>
    <listofallmembers>
      <member refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException_a19e08be1e69ac87230e739e784f3c6b6_1a19e08be1e69ac87230e739e784f3c6b6" prot="public" virt="non-virtual"><scope>Cqrs::Azure::DocumentDb::DocumentDbException</scope><name>DocumentDbException</name></member>
      <member refid="classCqrs_1_1Azure_1_1DocumentDb_1_1DocumentDbException_a0fe55ab6d2a689b055460557d4f50fe7_1a0fe55ab6d2a689b055460557d4f50fe7" prot="public" virt="non-virtual"><scope>Cqrs::Azure::DocumentDb::DocumentDbException</scope><name>DocumentDbException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
